package com.omagle.omagle;

/**
 * User class. Used to pair users, send data, and receive data through firebase.
 */

public class MyUser {
    String token; //unique token generated by firebase each time the app is opened
    boolean matched; //if a user is paired with another user
    String partner; //partner's token
    String avatar; //User's avatar of choice

    //default constructor
    public MyUser()
    {
        token ="";
        matched = false;
        partner = "Default partner";
        avatar = "UCSD 1";
    }

    //constructor based on unique identifier
    public MyUser(String t)
    {
        token = t;
        matched = false;
        partner = "Default partner";
        avatar = "UCSD 1";
    }

    //getter methods
    public String getToken()
    {
        return token;
    }

    public boolean getMatched()
    {
        return matched;
    }

    public String getPartner()
    {
        return partner;
    }

    public String getAvatar() { return avatar; }

    //setter methods

    public void setMatched(boolean m)
    {
        matched = m;
    }

    public void setPartner(String p)
    {
        partner = p;
    }

    public void setAvatar(String a) { avatar = a; }
}
